-- SEÇÃO DE USUÁRIOS --

CREATE TABLE PESSOA(
    ID_PES BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_PES DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_PES INT(11) NOT NULL DEFAULT 1,
    NOM_PES VARCHAR(255) NOT NULL,
    SOB_PES VARCHAR(255) NOT NULL,
    CPF_PES VARCHAR(14) NOT NULL UNIQUE,
    ATV_PES BIT(1) DEFAULT 1,
    CONSTRAINT PK_PESSOA PRIMARY KEY (ID_PES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USUARIO(
    ID_USR BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_USR DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_USR INT(11) NOT NULL DEFAULT 1,
    ATV_USR BIT(1) DEFAULT 1,
    USR_USR VARCHAR(255) UNIQUE NOT NULL,
    SEN_USR VARCHAR(255) NOT NULL,
    ID_PES BIGINT(20) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USR),
    CONSTRAINT FK_USUARIO_PESSOA FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE AUTORIDADE(
    ID_AUT BIGINT(20) NOT NULL AUTO_INCREMENT,
    AUT_AUT ENUM('ROLE_USUARIO', 'ROLE_ADMIN'),
    CONSTRAINT PK_AUTORIDADE PRIMARY KEY (ID_AUT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USUARIO_AUTORIDADE(
    ID_USR BIGINT(20) NOT NULL,
    ID_AUT BIGINT(20) NOT NULL,
    CONSTRAINT PK_USUARIO_AUTORIDADE PRIMARY KEY (ID_USR, ID_AUT),
    CONSTRAINT FK_USUARIO_AUTORIDADE_USUARIO FOREIGN KEY (ID_USR) REFERENCES USUARIO(ID_USR),
    CONSTRAINT FK_USUARIO_AUTORIDADE_AUTORIDADE FOREIGN KEY (ID_AUT) REFERENCES AUTORIDADE(ID_AUT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FOTO_PERFIL(
    ID_FOT BIGINT(20) NOT NULL AUTO_INCREMENT,
    ATV_FOT BIT(1) DEFAULT 1,
    IMG_CLI LONGBLOB,
    ID_USR BIGINT(20),
    CONSTRAINT PK_FOTO_PERFIL PRIMARY KEY (ID_FOT),
    CONSTRAINT FK_FOTO_PERFIL_USUARIO FOREIGN KEY (ID_USR) REFERENCES USUARIO(ID_USR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- SEÇÃO DE MEDICAMENTOS --
-- RECEITA --

CREATE TABLE MEDICO(
    ID_MED BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_MED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_MED INT(11) NOT NULL DEFAULT 1,
    ID_PES BIGINT(20) NOT NULL,
    CRM_MED VARCHAR(13) NOT NULL,
    CONSTRAINT PK_MEDICO PRIMARY KEY MEDICO(ID_MED),
    CONSTRAINT FK_MEDICO_PESSOA FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRINCIPIO_ATIVO(
    ID_PRI_ATV BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_PRI_ATV DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_PRI_ATV INT(11) NOT NULL DEFAULT 1,
    NOM_PRI_ATV VARCHAR(255),
    NOM_CIE_PRI_ATV VARCHAR(255),
    CONSTRAINT PK_PRINCIPIO_ATIVO PRIMARY KEY PRINCIPIO_ATIVO(ID_PRI_ATV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MEDICAMENTO(
    ID_MED BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_MED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_MED INT(11) NOT NULL DEFAULT 1,
    TIP_MED VARCHAR(255),
    CONSTRAINT PK_MEDICAMENTO PRIMARY KEY MEDICAMENTO(ID_MED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MEDICAMENTO_PRINCIPIO_ATIVO(
    ID_MED BIGINT(20) NOT NULL,
    ID_PRI_ATV BIGINT(20) NOT NULL,
    PROP_MED_PRI_ATV INT DEFAULT 0,
    CONSTRAINT PK_MEDICAMENTO_PRINCIPIO_ATIVO PRIMARY KEY
    MEDICAMENTO_PRINCIPIO_ATIVO(ID_MED, ID_PRI_ATV),
    CONSTRAINT FK_MEDICAMENTO_PRINCIPIO_ATIVO_MEDICAMENTO FOREIGN KEY (ID_MED) REFERENCES
    MEDICAMENTO(ID_MED),
    CONSTRAINT FK_MEDICAMENTO_PRINCIPIO_ATIVO_PRINCIPIO_ATIVO FOREIGN KEY (ID_PRI_ATV) REFERENCES
    PRINCIPIO_ATIVO(ID_PRI_ATV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE RECEITA(
    ID_REC BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_REC DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REC INT(11) NOT NULL DEFAULT 1,
    VAL_REC DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_MED BIGINT(20) NOT NULL,
    ID_PES BIGINT(20) NOT NULL,
    ID_USR BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA PRIMARY KEY RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_MEDICO FOREIGN KEY (ID_MED) REFERENCES MEDICO(ID_MED),
    CONSTRAINT FK_RECEITA_USUARIO FOREIGN KEY (ID_USR) REFERENCES USUARIO(ID_USR),
    CONSTRAINT FK_RECEITA_PESSOA FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RECEITA_MEDICAMENTO(
    ID_REC BIGINT(20) NOT NULL,
    ID_MED BIGINT(20) NOT NULL,
    QTD_REC_MED DECIMAL(19,2) DEFAULT 0,
    PES_REC_MED DECIMAL(19,2) NOT NULL,
    LOT_REC_MED BIGINT(20) NOT NULL,
    POS_REC_MED VARCHAR(255),
    VAL_REC_MED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_RECEITA_MEDICAMENTO PRIMARY KEY
    RECEITA_MEDICAMENTO(ID_MED, ID_REC),
    CONSTRAINT FK_RECEITA_MEDICAMENTO_MEDICAMENTO FOREIGN KEY (ID_MED) REFERENCES
    MEDICAMENTO(ID_MED),
    CONSTRAINT FK_RECEITA_MEDICAMENTO_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- OUTRAS TABELAS --
CREATE TABLE LOG(
    ID_LOG BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_LOG DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_LOG INT(11) NOT NULL DEFAULT 1,
    ID_USR BIGINT(20) NOT NULL,
    ACT_LOG INT(11) NOT NULL,
    ID_ACT_LOG BIGINT(20) NOT NULL,
    DES_ACT_LOG VARCHAR(255) DEFAULT '',
    CONSTRAINT PK_LOG PRIMARY KEY LOG(ID_LOG),
    CONSTRAINT FK_LOG_USUARIO FOREIGN KEY (ID_LOG) REFERENCES USUARIO(ID_USR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;