-- SEÇÃO DE USUÁRIOS --
CREATE TABLE PESSOA(
    ID_PES BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_PES DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_PES INT(11) NOT NULL DEFAULT 1,
    NOM_PES VARCHAR(255) NOT NULL,
    SOB_PES VARCHAR(255) NOT NULL,
    CPF_PES VARCHAR(14) NOT NULL UNIQUE,
    ATV_PES BIT(1) DEFAULT 1,
    CONSTRAINT PK_PESSOA PRIMARY KEY (ID_PES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE USUARIO(
    ID_USR BIGINT(20) NOT NULL AUTO_INCREMENT,
    ATV_USR BIT(1) DEFAULT 1,
    USR_USR VARCHAR(255) UNIQUE NOT NULL,
    SEN_USR VARCHAR(255) NOT NULL,
    ID_PES BIGINT(20) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USR),
    CONSTRAINT FK_USUARIO_PESSOA FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE AUTORIDADE(
    ID_AUT BIGINT(20) NOT NULL AUTO_INCREMENT,
    AUT_AUT ENUM('ROLE_USUARIO', 'ROLE_ADMIN'),
    CONSTRAINT PK_AUTORIDADE PRIMARY KEY (ID_AUT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE USUARIO_AUTORIDADE(
    ID_USR BIGINT(20) NOT NULL,
    ID_AUT BIGINT(20) NOT NULL,
    CONSTRAINT PK_USUARIO_AUTORIDADE PRIMARY KEY (ID_USR, ID_AUT),
    CONSTRAINT FK_USUARIO_AUTORIDADE_USUARIO FOREIGN KEY (ID_USR) REFERENCES USUARIO(ID_USR),
    CONSTRAINT FK_USUARIO_AUTORIDADE_AUTORIDADE FOREIGN KEY (ID_AUT) REFERENCES AUTORIDADE(ID_AUT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE FOTO_PERFIL(
    ID_FOT BIGINT(20) NOT NULL AUTO_INCREMENT,
    ATV_FOT BIT(1) DEFAULT 1,
    IMG_CLI LONGBLOB,
    ID_USR BIGINT(20),
    CONSTRAINT PK_FOTO_PERFIL PRIMARY KEY (ID_FOT),
    CONSTRAINT FK_FOTO_PERFIL_USUARIO FOREIGN KEY (ID_USR) REFERENCES USUARIO(ID_USR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- SEÇÃO DE MEDICAMENTOS --
-- CAPSULA --
CREATE TABLE CAPSULA(
    ID_CAP BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_CAP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_CAP INT(11) NOT NULL DEFAULT 1,
    NOM_CIE_CAP VARCHAR(255) NOT NULL,
    NOM_CAP VARCHAR(255) NOT NULL,
    DUR_LOT_CAP BIGINT(20) DEFAULT NULL,
    PES_MAX_CAP DECIMAL(19,4) DEFAULT 0,
    PES_MIN_CAP DECIMAL(19,4) DEFAULT 0,
    CONSTRAINT PK_CAPSULA PRIMARY KEY (ID_CAP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE CAPSULA_ESTOQUE(
    ID_CAP_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_CAP_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_CAP_EST INT(11) NOT NULL DEFAULT 1,
    QTD_CAP_EST DECIMAL(19,2) DEFAULT 0,
    LOT_CAP_EST BIGINT(20) DEFAULT 0,
    DAT_CRI_LOT_CAP_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DAT_VEN_LOT_CAP_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_CAP BIGINT(20) NOT NULL,
    CONSTRAINT PK_CAPSULA_ESTOQUE PRIMARY KEY CAPSULA_ESTOQUE(ID_CAP_EST),
    CONSTRAINT FK_CAPSULA_ESTOQUE_CAPSULA FOREIGN KEY (ID_CAP) REFERENCES CAPSULA(ID_CAP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE CAPSULA_USO_ESTOQUE(
    ID_CAP_USO_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_CAP_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_CAP_USO_EST INT(11) NOT NULL DEFAULT 1,
    VAL_CAP_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    QTD_CAP_USO_EST DECIMAL(19,2) DEFAULT 0,
    POS_CAP_USO_EST VARCHAR(255),
    ID_CAP_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_CAPSULA_USO_ESTOQUE PRIMARY KEY CAPSULA_USO_ESTOQUE(ID_CAP_USO_EST),
    CONSTRAINT FK_CAPSULA_USO_ESTOQUE_CAPSULA_ESTOQUE FOREIGN KEY (ID_CAP_EST)
    REFERENCES CAPSULA_ESTOQUE(ID_CAP_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- HOMEOPARIA --
CREATE TABLE HOMEOPATIA(
    ID_HOM BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_HOM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_HOM INT(11) NOT NULL DEFAULT 1,
    NOM_HOM VARCHAR(255) NOT NULL,
    CONSTRAINT PK_HOMEOPATIA PRIMARY KEY HOMEOPATIA(ID_HOM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE HOMEOPATIA_DOSAGEM (
    ID_HOM_DOS BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_HOM_DOS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_HOM_DOS INT(11) NOT NULL DEFAULT 1,
    ID_HOM BIGINT(20) NOT NULL,
    DIL_HOM_DOS INT(11) NOT NULL DEFAULT 0,
    CONSTRAINT PK_HOMEOPATIA_DOSAGEM PRIMARY KEY HOMEOPATIA_DOSAGEM(ID_HOM_DOS),
    CONSTRAINT FK_HOMEOPATIA_DOSAGEM_HOMEOPATIA FOREIGN KEY (ID_HOM) REFERENCES HOMEOPATIA(ID_HOM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE HOMEOPATIA_DOSAGEM_USO(
    ID_HOM_DOS_USO BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_HOM_DOS_USO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_HOM_DOS_USO INT(11) NOT NULL DEFAULT 1,
    VAL_HOM_DOS_USO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    QTD_HOM_DOS_USO DECIMAL(19,2) DEFAULT 0,
    POS_HOM_DOS_USO VARCHAR(255),
    ID_HOM_DOS BIGINT(20) NOT NULL,
    CONSTRAINT PK_HOMEOPATIA_DOSAGEM_USO PRIMARY KEY
    HOMEOPATIA_DOSAGEM_USO_ESTOQUE(ID_HOM_DOS_USO),
    CONSTRAINT FK_HOMEOPATIA_DOSAGEM_USO_HOMEOPATIA_DOSAGEM FOREIGN KEY (ID_HOM_DOS)
    REFERENCES HOMEOPATIA_DOSAGEM(ID_HOM_DOS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- POMADA --
CREATE TABLE POMADA(
    ID_POM BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_POM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_POM INT(11) NOT NULL DEFAULT 1,
    NOM_CIE_POM VARCHAR(255) NOT NULL,
    NOM_POM VARCHAR(255) NOT NULL,
    DUR_LOT_POM BIGINT(20) DEFAULT NULL,
    CONSTRAINT PK_POMADA PRIMARY KEY POMADA(ID_POM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE POMADA_ESTOQUE(
    ID_POM_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_POM_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_POM_EST INT(11) NOT NULL DEFAULT 1,
    QTD_POM_EST DECIMAL(19,2) DEFAULT 0,
    ID_POM BIGINT(20) NOT NULL,
    CONSTRAINT PK_POMADA_ESTOQUE PRIMARY KEY POMADA_ESTOQUE(ID_POM_EST),
    CONSTRAINT FK_POMADA_ESTOQUE_POMADA FOREIGN KEY (ID_POM) REFERENCES POMADA(ID_POM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE POMADA_USO_ESTOQUE(
    ID_POM_USO_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_POM_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_POM_USO_EST INT(11) NOT NULL DEFAULT 1,
    QTD_POM_USO_EST DECIMAL(19,2) DEFAULT 0,
    VAL_POM_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_POM_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_POMADA_USO_ESTOQUE PRIMARY KEY POMADA_USO_ESTOQUE(ID_POM_USO_EST),
    CONSTRAINT FK_POMADA_USO_ESTOQUE_POMADA_ESTOQUE FOREIGN KEY (ID_POM_EST)
    REFERENCES POMADA_ESTOQUE(ID_POM_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE POMADA_SEM_CONTROLE(
    ID_POM_SEM_CTL BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_POM_SEM_CTL DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_POM_SEM_CTL INT(11) NOT NULL DEFAULT 1,
    QTD_POM_SEM_CTL DECIMAL(19,2) DEFAULT 0,
    NOM_POM_SEM_CTL VARCHAR(255) NOT NULL,
    CONSTRAINT PK_POMADA_SEM_CONTROLE PRIMARY KEY
    POMADA_SEM_CONTROLE(ID_POM_SEM_CTL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- OUTROS MEDICAMENTOS --
CREATE TABLE OUTROS_MEDICAMENTOS(
    ID_OUT_MED BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_OUT_MED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_OUT_MED INT(11) NOT NULL DEFAULT 1,
    NOM_OUT_MED VARCHAR(255) NOT NULL,
    TIP_MED_OUT_MED ENUM('EXTRATO_AQUOSO','OLEOS_MEDICINAIS','SABONETE', 'SHAMPOO', 'SOLUCAO_NASAL',
     'XAROPE', 'CHA', 'CAPSULA','MEDICAMENTOS', 'OUTROS'),
     CONSTRAINT PK_OUTROS_MEDICAMENTOS PRIMARY KEY OUTROS_MEDICAMENTOS(ID_OUT_MED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE OUTROS_MEDICAMENTOS_ESTOQUE(
    ID_OUT_MED_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_OUT_MED_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_OUT_MED_EST INT(11) NOT NULL DEFAULT 1,
    QTD_OUT_MED_EST DECIMAL(19,2) DEFAULT 0,
    ID_OUT_MED BIGINT(20) NOT NULL,
    LOT_OUT_MED_EST BIGINT(20) DEFAULT 0,
    DAT_CRI_LOT_OUT_MED_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DAT_VEN_LOT_OUT_MED_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OUTROS_MEDICAMENTOS_ESTOQUE
    PRIMARY KEY OUTROS_MEDICAMENTOS_ESTOQUE(ID_OUT_MED_EST),
    CONSTRAINT FK_OUTROS_MEDICAMENTOS_ESTOQUE_OUTROS_MEDICAMENTOS FOREIGN KEY (ID_OUT_MED)
    REFERENCES OUTROS_MEDICAMENTOS(ID_OUT_MED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE OUTROS_MEDICAMENTOS_USO_ESTOQUE(
    ID_OUT_MED_USO_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_OUT_MED_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_OUT_MED_USO_EST INT(11) NOT NULL DEFAULT 1,
    QTD_OUT_MED_USO_EST DECIMAL(19,2) DEFAULT 0,
    VAL_OUT_MED_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_OUT_MED_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_OUTROS_MEDICAMENTOS_USO_ESTOQUE
    PRIMARY KEY OUTROS_MEDICAMENTOS_USO_ESTOQUE(ID_OUT_MED_USO_EST),
    CONSTRAINT FK_OUTROS_MEDICAMENTOS_USO_ESTOQUE_OUTROS_MEDICAMENTOS_ESTOQUE
    FOREIGN KEY (ID_OUT_MED_EST) REFERENCES OUTROS_MEDICAMENTOS_ESTOQUE(ID_OUT_MED_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- PLANTA DESIDRATADA --
CREATE TABLE PLANTA_DESIDRATADA (
    ID_PLT_DES BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_PLT_DES DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_PLT_DES INT(11) NOT NULL DEFAULT 1,
    NOM_CIE_PLT_DES VARCHAR(255) NOT NULL,
    NOM_PLT_DES VARCHAR(255) NOT NULL,
    DUR_LOT_PLT_DES BIGINT(20) DEFAULT NULL,
    CONSTRAINT PK_PLANTA_DESIDRATADA PRIMARY KEY PLANTA_DESIDRATADA(ID_PLT_DES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE PLANTA_DESIDRATADA_ESTOQUE(
    ID_PLT_DES_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_PLT_DES_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_PLT_DES_EST INT(11) NOT NULL DEFAULT 1,
    QTD_PLT_DES_EST DECIMAL(19,2) DEFAULT 0,
    LOT_PLT_DES_EST BIGINT(20) DEFAULT 0,
    DAT_CRI_LOT_PLT_DES_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DAT_VEN_LOT_PLT_DES_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_PLT_DES BIGINT(20) NOT NULL,
    CONSTRAINT PK_PLANTA_DESIDRATADA_ESTOQUE PRIMARY KEY PLANTA_DESIDRATADA_ESTOQUE(ID_PLT_DES_EST),
    CONSTRAINT FK_PLANTA_DESIDRATADA_ESTOQUE_PLANTA_DESIDRATADA FOREIGN KEY (ID_PLT_DES)
    REFERENCES PLANTA_DESIDRATADA(ID_PLT_DES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE PLANTA_DESIDRATADA_USO_ESTOQUE(
    ID_PLT_DES_USO_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_PLT_DES_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_PLT_DES_USO_EST INT(11) NOT NULL DEFAULT 1,
    VAL_PLT_DES_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    QTD_PLT_DES_USO_EST DECIMAL(19,2) DEFAULT 0,
    POS_PLT_DES_USO_EST VARCHAR(255),
    ID_PLT_DES_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_PLANTA_DESIDRATADA_USO_ESTOQUE
    PRIMARY KEY PLANTA_DESIDRATADA_USO_ESTOQUE(ID_PLT_DES_USO_EST),
    CONSTRAINT FK_PLANTA_DESIDRATADA_USO_ESTOQUE_PLANTA_DESIDRATADA_ESTOQUE
    FOREIGN KEY (ID_PLT_DES_EST) REFERENCES PLANTA_DESIDRATADA_ESTOQUE(ID_PLT_DES_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- FLORAL --
CREATE TABLE FLORAL(
    ID_FLO BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_FLO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_FLO INT(11) NOT NULL DEFAULT 1,
    NOM_FLO VARCHAR(255) NOT NULL,
    CONSTRAINT PK_FLORAL PRIMARY KEY FLORAL(ID_FLO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE FLORAL_USO(
    ID_FLO_USO BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_FLO_USO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_FLO_USO INT(11) NOT NULL DEFAULT 1,
    QTD_FLO_USO DECIMAL(19,2) DEFAULT 0,
    VAL_FLO_USO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_FLO BIGINT(20) NOT NULL,
    CONSTRAINT PK_FLORAL_USO PRIMARY KEY FLORAL_USO(ID_FLO_USO),
    CONSTRAINT FK_FLORAL_USO_FLORAL FOREIGN KEY (ID_FLO) REFERENCES FLORAL(ID_FLO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- MULTIMISTURA --
CREATE TABLE MULTIMISTURA(
    ID_MUM BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_MUM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_MUM INT(11) NOT NULL DEFAULT 1,
    NOM_MUM VARCHAR(255) NOT NULL,
    CONSTRAINT PK_MULTIMISTURA PRIMARY KEY MULTIMISTURA(ID_MUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE MULTIMISTURA_USO(
    ID_MUM_USO BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_MUM_USO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_MUM_USO INT(11) NOT NULL DEFAULT 1,
    QTD_MUM_USO DECIMAL(19,2) DEFAULT 0,
    VAL_MUM_USO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_MUM BIGINT(20) NOT NULL,
    CONSTRAINT PK_MULTIMISTURA_USO PRIMARY KEY MULTIMISTURA_USO(ID_MUM_USO),
    CONSTRAINT FK_MULTIMISTURA_USO_FLORAL FOREIGN KEY (ID_MUM) REFERENCES MULTIMISTURA(ID_MUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- RECEITA --
CREATE TABLE MEDICO(
    ID_MED BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_MED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_MED INT(11) NOT NULL DEFAULT 1,
    ID_PES BIGINT(20) NOT NULL,
    CRM_MED VARCHAR(13) NOT NULL,
    CONSTRAINT PK_MEDICO PRIMARY KEY MEDICO(ID_MED),
    CONSTRAINT FK_MEDICO_PESSOA FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA(
    ID_REC BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_REC DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_REC INT(11) NOT NULL DEFAULT 1,
    VAL_REC DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_MED BIGINT(20) NOT NULL,
    ID_PES BIGINT(20) NOT NULL,
    ID_USR BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA PRIMARY KEY RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_MEDICO FOREIGN KEY (ID_MED) REFERENCES MEDICO(ID_MED),
    CONSTRAINT FK_RECEITA_USUARIO FOREIGN KEY (ID_USR) REFERENCES USUARIO(ID_USR),
    CONSTRAINT FK_RECEITA_PESSOA FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_POMADA(
    ID_REC BIGINT(20) NOT NULL,
    ID_POM_USO_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_POMADA PRIMARY KEY RECEITA_POMADA(ID_REC, ID_POM_USO_EST),
    CONSTRAINT FK_RECEITA_POMADA_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_POMADA_POMADA FOREIGN KEY (ID_POM_USO_EST) REFERENCES
    POMADA_USO_ESTOQUE(ID_POM_USO_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_POMADA_SEM_CONTROLE(
    ID_REC BIGINT(20) NOT NULL,
    ID_POM_SEM_CTL BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_POMADA_SEM_CONTROLE PRIMARY KEY RECEITA_POMADA(ID_REC, ID_POM_SEM_CTL),
    CONSTRAINT FK_RECEITA_POMADA_SEM_CONTROLE_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_POMADA_SEM_CONTROLE_POMADA_SEM_CONTROLE FOREIGN KEY (ID_POM_SEM_CTL) REFERENCES
    POMADA_SEM_CONTROLE(ID_POM_SEM_CTL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_PLANTA_DESIDRATADA(
    ID_REC BIGINT(20) NOT NULL,
    ID_PLT_DES_USO_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_PLANTA_DESIDRATADA
    PRIMARY KEY RECEITA_PLANTA_DESIDRATADA(ID_REC, ID_PLT_DES_USO_EST),
    CONSTRAINT FK_RECEITA_PLANTA_DESIDRATADA_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_PLANTA_DESIDRATADA_PLANTA_DESIDRATADAFOREIGN FOREIGN KEY (ID_PLT_DES_USO_EST)
    REFERENCES PLANTA_DESIDRATADA_USO_ESTOQUE(ID_PLT_DES_USO_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_HOMEOPATIA(
    ID_REC BIGINT(20) NOT NULL,
    ID_HOM_DOS_USO BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_HOMEOPATIA PRIMARY KEY RECEITA_HOMEOPATIA(ID_REC, ID_HOM_DOS_USO),
    CONSTRAINT FK_RECEITA_HOMEOPATIA_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_HOMEOPATIA_HOMEOPATIA FOREIGN KEY (ID_HOM_DOS_USO) REFERENCES
    HOMEOPATIA_DOSAGEM_USO(ID_HOM_DOS_USO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_FLORAL(
    ID_REC BIGINT(20) NOT NULL,
    ID_FLO_USO BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_FLORAL PRIMARY KEY RECEITA_FLORAL(ID_REC, ID_FLO_USO),
    CONSTRAINT FK_RECEITA_FLORAL_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_FLORAL_FLORAL FOREIGN KEY (ID_FLO_USO) REFERENCES
    FLORAL_USO(ID_FLO_USO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_MULTIMISTURA(
    ID_REC BIGINT(20) NOT NULL,
    ID_MUM_USO BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_MULTIMISTURA PRIMARY KEY RECEITA_MULTIMISTURA(ID_REC, ID_MUM_USO),
    CONSTRAINT FK_RECEITA_MULTIMISTURA_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_MULTIMISTURA_MULTIMISTURA FOREIGN KEY (ID_MUM_USO) REFERENCES
    MULTIMISTURA_USO(ID_MUM_USO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_CAPSULA(
    ID_REC BIGINT(20) NOT NULL,
    ID_CAP_USO_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_CAPSULA PRIMARY KEY RECEITA_CAPSULA(ID_REC, ID_CAP_USO_EST),
    CONSTRAINT FK_RECEITA_CAPSULA_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_CAPSULA_CAPSULA FOREIGN KEY (ID_CAP_USO_EST) REFERENCES
    CAPSULA_USO_ESTOQUE(ID_CAP_USO_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_OUTROS_MEDICAMENTOS(
    ID_REC BIGINT(20) NOT NULL,
    ID_OUT_MED_USO_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_OUTROS_MEDICAMENTOS
    PRIMARY KEY RECEITA_OUTROS_MEDICAMENTOS(ID_REC, ID_OUT_MED_USO_EST),
    CONSTRAINT FK_RECEITA_OUTROS_MEDICAMENTOS_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_OUTROS_MEDICAMENTOS_OUTROS_MEDICAMENTOS FOREIGN KEY (ID_OUT_MED_USO_EST)
    REFERENCES OUTROS_MEDICAMENTOS_USO_ESTOQUE(ID_OUT_MED_USO_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- TINTURA --
CREATE TABLE TINTURA(
    ID_TIN BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_TIN DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_TIN INT(11) NOT NULL DEFAULT 1,
    NOM_TIN VARCHAR(255) NOT NULL,
    NOM_CIE_TIN VARCHAR(255),
    CONSTRAINT PK_TINTURA PRIMARY KEY TINTURA(ID_TIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE TINTURA_DOSAGEM (
    ID_TIN_DOS BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_TIN_DOS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_TIN_DOS INT(11) NOT NULL DEFAULT 1,
    DUR_LOT_TIN_DOS BIGINT(20) DEFAULT NULL,
    ID_TIN BIGINT(20) NOT NULL,
    DIL_TIN_DOS INT(11) NOT NULL DEFAULT 0,
    TIP_DIL_TIN_DOS ENUM('CH','DH') DEFAULT 'CH',
    CONSTRAINT PK_TINTURA_DOSAGEM PRIMARY KEY TINTURA_DOSAGEM(ID_TIN_DOS),
    CONSTRAINT FK_TINTURA_DOSAGEM_TINTURA FOREIGN KEY (ID_TIN) REFERENCES TINTURA(ID_TIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE TINTURA_DOSAGEM_ESTOQUE(
    ID_TIN_DOS_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_TIN_DOS_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_TIN_DOS_EST INT(11) NOT NULL DEFAULT 1,
    QTD_TIN_DOS_EST DECIMAL(19,2) DEFAULT 0,
    LOT_TIN_DOS_EST BIGINT(20) DEFAULT 0,
    DAT_CRI_LOT_TIN_DOS_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DAT_VEN_LOT_TIN_DOS_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_TIN_DOS BIGINT(20) NOT NULL,
    CONSTRAINT PK_TINTURA_DOSAGEM_ESTOQUE PRIMARY KEY TINTURA_DOSAGEM_ESTOQUE(ID_TIN_DOS_EST),
    CONSTRAINT FK_TINTURA_DOSAGEM_ESTOQUE_TINTURA_DOSAGEM FOREIGN KEY (ID_TIN_DOS)
    REFERENCES TINTURA_DOSAGEM(ID_TIN_DOS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE TINTURA_DOSAGEM_USO_ESTOQUE(
    ID_TIN_DOS_USO_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_TIN_DOS_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_TIN_DOS_USO_EST INT(11) NOT NULL DEFAULT 1,
    VAL_TIN_DOS_USO_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    QTD_TIN_DOS_USO_EST DECIMAL(19,2) DEFAULT 0,
    POS_TIN_DOS_USO_EST VARCHAR(255),
    ID_TIN_DOS_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_TINTURA_DOSAGEM_USO_ESTOQUE PRIMARY KEY
    TINTURA_DOSAGEM_USO_ESTOQUE(ID_TIN_DOS_USO_EST),
    CONSTRAINT FK_TINTURA_DOSAGEM_USO_ESTOQUE_TINTURA_DOSAGEM_ESTOQUE
    FOREIGN KEY (ID_TIN_DOS_EST) REFERENCES TINTURA_DOSAGEM_ESTOQUE(ID_TIN_DOS_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE TINTURA_USO_MISTURA_RECEITA(
    ID_TIN_USO_MIS_REC BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_TIN_USO_MIS_REC DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_TIN_USO_MIS_REC INT(11) NOT NULL DEFAULT 1,
    QTD_TIN_USO_MIS_REC DECIMAL(19,2) DEFAULT 0,
    ID_REC BIGINT(20) NOT NULL,
    CONSTRAINT PK_TINTURA_USO_MISTURA_RECEITA PRIMARY KEY
    TINTURA_USO_MISTURA_RECEITA(ID_TIN_USO_MIS_REC),
    CONSTRAINT FK_TINTURA_USO_MISTURA_RECEITA_RECEITA
    FOREIGN KEY (ID_REC) REFERENCES RECEITA(ID_REC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE TINTURA_USO_MISTURA(
    ID_TIN_USO_MIS BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_TIN_USO_MIS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_TIN_USO_MIS INT(11) NOT NULL DEFAULT 1,
    PROP_TIN_USO_MIS DECIMAL(19,2) DEFAULT 0,
    ID_TIN_DOS_USO_EST BIGINT(20) NOT NULL,
    ID_TIN_USO_MIS_REC BIGINT(20) NOT NULL,
    CONSTRAINT PK_TINTURA_USO_MISTURA PRIMARY KEY
    TINTURA_USO_MISTURA(ID_TIN_USO_MIS),
    CONSTRAINT FK_TINTURA_USO_MISTURA_TINTURA_DOSAGEM_USO_ESTOQUE
    FOREIGN KEY (ID_TIN_DOS_USO_EST) REFERENCES TINTURA_DOSAGEM_USO_ESTOQUE(ID_TIN_DOS_USO_EST),
    CONSTRAINT FK_TINTURA_USO_MISTURA_TINTURA_USO_MISTURA_RECEITA
    FOREIGN KEY (ID_TIN_USO_MIS_REC) REFERENCES TINTURA_USO_MISTURA_RECEITA(ID_TIN_USO_MIS_REC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE RECEITA_TINTURA(
    ID_REC BIGINT(20) NOT NULL,
    ID_TIN_DOS_USO_EST BIGINT(20) NOT NULL,
    CONSTRAINT PK_RECEITA_TINTURA PRIMARY KEY RECEITA_TINTURA(ID_REC, ID_TIN_DOS_USO_EST),
    CONSTRAINT FK_RECEITA_TINTURA_RECEITA FOREIGN KEY (ID_REC) REFERENCES
    RECEITA(ID_REC),
    CONSTRAINT FK_RECEITA_TINTURA_TINTURA FOREIGN KEY (ID_TIN_DOS_USO_EST) REFERENCES
    TINTURA_DOSAGEM_USO_ESTOQUE(ID_TIN_DOS_USO_EST)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- OUTRAS TABELAS --
CREATE TABLE LOG(
    ID_LOG BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_LOG DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_LOG INT(11) NOT NULL DEFAULT 1,
    ID_USR BIGINT(20) NOT NULL,
    ACT_LOG INT(11) NOT NULL,
    ID_ACT_LOG BIGINT(20) NOT NULL,
    DES_ACT_LOG VARCHAR(255) DEFAULT '',
    CONSTRAINT PK_LOG PRIMARY KEY LOG(ID_LOG),
    CONSTRAINT FK_LOG_USUARIO FOREIGN KEY (ID_LOG) REFERENCES USUARIO(ID_USR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;