
CREATE TABLE HOMEOPATIA_DOSAGEM_ESTOQUE(
    ID_HOM_DOS_EST BIGINT(20) NOT NULL AUTO_INCREMENT,
    DAT_CRI_HOM_DOS_EST DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VER_HOM_DOS_EST INT(11) NOT NULL DEFAULT 1,
    QTD_HOM_DOS_EST DECIMAL(19,2) DEFAULT 0,
    ID_HOM_DOS BIGINT(20) NOT NULL,
    CONSTRAINT PK_HOMEOPATIA_DOSAGEM_ESTOQUE PRIMARY KEY HOMEOPATIA_DOSAGEM_ESTOQUE(ID_HOM_DOS_EST),
    CONSTRAINT FK_HOMEOPATIA_DOSAGEM_ESTOQUE_HOMEOPATIA_DOSAGEM FOREIGN KEY (ID_HOM_DOS)
    REFERENCES HOMEOPATIA_DOSAGEM(ID_HOM_DOS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;